### ISSUE TITLE
Obsolete opal server image

### ISSUE THREAD

**Issue by SalomeLefebvre** [treedomtrees/opal-fetcher-mongodb#6]
I tried starting the project by using the docker compose file, I'm getting this error :
![image](https://github.com/user-attachments/assets/bc220f6e-310a-45a5-a8c3-0186809984cd)
related to this part in the DockerFile :
![image](https://github.com/user-attachments/assets/3154dad9-5f57-4ebe-ab36-cb20b2df34bb)

**Comment by OancaAndrei** [comment]
Hi! Thanks for your interest. Looks like the team at Permit moved around their images, as you can [see here](https://github.com/permitio/opal-fetcher-postgres/commit/58223e4edc8d092247f51bcfc9dbbdb4e7ad55d5).

Could you try replicating those changes and see if anything changes?

We will be updating this repo as well in the following days. But if you beat us to it feel free to open a PR! 😄

**Comment by SalomeLefebvre** [comment]
Thank you for your reponse !

I can now start Docker Compose, but it appears that the MongoDB server is unreachable to the opal client, even though I can connect to the database directly. I'm encountering this error: 

![image](https://github.com/user-attachments/assets/6e7dc5b7-4080-4ccd-bbc2-995f15c06115)
![image](https://github.com/user-attachments/assets/1681701d-25d9-43c4-a899-d763cf5d4cc0)
![image](https://github.com/user-attachments/assets/8ee9981a-2049-4077-9d41-b47cb241af77)
![image](https://github.com/user-attachments/assets/549cc9a4-11b0-4da9-a01d-7657e3cc0e37)

Could this be an issue on my side ?

**Comment by OancaAndrei** [comment]
Hi @SalomeLefebvre, we just released version `1.0.0` of the fetcher which should address the issues you faced.

Feel free to reopen this issue if you still encounter errors.
